---
- name: Install dev packages
  become: true
  package:
    state: present
    name:
      - jq
      - ripgrep
      - hub
      - luarocks
      - fzf
      - fzy
      - htop
      - delve
      - ninja-build
      - g++
