---
- name: Install dev packages
  become: true
  package:
    state: present
    name:
      - build-essential
      - jq
      - ripgrep
      - hub
      - luarocks
      - fzf
      - fzy
      - htop
      - delve
      - ninja-build
      - g++
      - openjdk-17-jre
      - nodejs
      - npm
      - ruby-full
      - zlib1g-dev
