---
- name: Gathering facts
  gather_facts:
- name: Install stow
  become: true
  package:
    name: stow
    state: present
- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config/nvim
    - ~/bin
    - ~/apps
    - ~/.zsh/completion
    - ~/.zsh/plugins
- name: Create git symlinks
  shell: stow -v -t ~ git 
  args:
    chdir: ~/dotfiles
- name: Create shell symlinks
  shell: stow -v -t ~ shell 
  args:
    chdir: ~/dotfiles
- name: Create vim symlinks
  shell: stow -v -t ~ vim 
  args:
    chdir: ~/dotfiles
- name: Init dircolors
  shell: dircolors -p >! ~/.dircolors
  args:
    executable: /usr/bin/zsh
    creates: ~/.dircolors
