---
- name: Clone tree-sitter repos
  git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/dev/{{ item.repo }}
    version: '{{ item.version }}'
    force: true
  loop:
    - { repo: 'tree-sitter/tree-sitter-java', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-python', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-html', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-json', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-c-sharp', version: 'master' }
    - { repo: 'stsewd/tree-sitter-rst', version: 'master' }
    - { repo: 'ikatyang/tree-sitter-markdown', version: 'master' }
    - { repo: 'vigoux/tree-sitter-viml', version: 'master' }
- name: Ensure nvim parser and query folders exists
  file:
    path: ~/.config/nvim/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - parser/
    - queries/
    - queries/java
    - queries/python
    - queries/rst
    - queries/html
    - queries/json
    - queries/markdown
    - queries/vim
    - queries/c_sharp

- name: Generate parsers
  shell: tree-sitter generate --abi 14 && cc -O2 -o ~/.config/nvim/parser/{{ item.ft }}.so -I./src {{ item.files }} -shared -Os -lstdc++ -fPIC
  args:
    chdir: ~/dev/{{ item.repo }}
  loop:
    - repo: 'tree-sitter/tree-sitter-java'
      ft: 'java'
      files: src/parser.c
    - repo: 'tree-sitter/tree-sitter-python'
      ft: 'python'
      files: src/parser.c src/scanner.cc
    - repo: 'tree-sitter/tree-sitter-html'
      ft: 'html'
      files: src/parser.c src/scanner.cc
    - repo: 'stsewd/tree-sitter-rst'
      ft: 'rst'
      files: src/parser.c src/scanner.c
    - repo: 'tree-sitter/tree-sitter-json'
      ft: 'json'
      files: src/parser.c
    - repo: 'ikatyang/tree-sitter-markdown'
      ft: 'markdown'
      files: src/parser.c src/scanner.cc
    - repo: 'vigoux/tree-sitter-viml'
      ft: 'vim'
      files: src/parser.c src/scanner.c
    - repo: 'tree-sitter/tree-sitter-c-sharp'
      ft: 'c_sharp'
      files: src/parser.c src/scanner.c

- name: Copy queries
  copy:
    src: ~/dev/{{ item.src_dir }}/{{ item.file }}
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.file }}
    mode: 0644
  loop:
    - { ft: 'java', src_dir: 'tree-sitter/tree-sitter-java/queries', file: 'tags.scm' }
    - { ft: 'html', src_dir: 'tree-sitter/tree-sitter-html/queries', file: 'highlights.scm' }

- name: Fetch queries
  get_url:
    url: https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/{{ item.ft }}/{{ item.name }}.scm
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.name }}.scm
  loop:
    - { ft: 'json', name: 'highlights' }
    - { ft: 'java', name: 'highlights' }
    - { ft: 'java', name: 'locals' }
    - { ft: 'python', name: 'highlights' }
    - { ft: 'python', name: 'locals' }
    - { ft: 'markdown', name: 'highlights' }
    - { ft: 'markdown', name: 'injections' }
    - { ft: 'rst', name: 'highlights' }
    - { ft: 'rst', name: 'injections' }
    - { ft: 'vim', name: 'highlights' }
    - { ft: 'vim', name: 'injections' }
    - { ft: 'vim', name: 'locals' }

- name: Fetch csharp queries
  get_url:
    url: https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/c_sharp/{{ item }}.scm
    dest: ~/.config/nvim/queries/c_sharp/{{ item }}.scm
  loop:
    - highlights
    - injections
    - locals
