---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory

- name: Install jdk 17
  unarchive:
    src: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.2_8.tar.gz
    dest: ~/.local/jdks
    creates: ~/.local/jdks/jdk-17.0.2+8
    remote_src: true

- name: Install jdk 18
  unarchive:
    src: https://github.com/adoptium/temurin18-binaries/releases/download/jdk-18%2B36/OpenJDK18U-jdk_x64_linux_hotspot_18_36.tar.gz
    dest: ~/.local/jdks
    creates: ~/.local/jdks/jdk-18+36
    remote_src: true


