---
- name: Setup neovim virtualenv
  pip:
    name:
      - pynvim
      - neovim-remote
    virtualenv: ~/.virtualenvs/nvim
    virtualenv_command: /usr/bin/python3 -m venv
- name: Symlink neovim remote
  file:
    src: ~/.virtualenvs/nvim/bin/nvr
    dest: ~/bin/nvr
    state: link

- name: Checkout vim plugins
  git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/.config/nvim/pack/plugins/{{ item.folder }}/{{ item.repo | basename }}
  async: 120
  poll: 0
  register: git_clone
  loop:
    - { folder: start, repo: junegunn/gv.vim }
    - { folder: start, repo: junegunn/vim-easy-align }
    - { folder: start, repo: tpope/vim-fugitive }
    - { folder: start, repo: tpope/vim-rhubarb }
    - { folder: start, repo: gpanders/editorconfig.nvim }
    - { folder: start, repo: AndrewRadev/linediff.vim }
    - { folder: start, repo: AndrewRadev/splitjoin.vim }
    - { folder: start, repo: hynek/vim-python-pep8-indent }
    - { folder: start, repo: jamessan/vim-gnupg }
    - { folder: start, repo: L3MON4D3/LuaSnip }
    - { folder: start, repo: liuchengxu/vista.vim }
    - { folder: start, repo: janko-m/vim-test }
    - { folder: start, repo: phaazon/hop.nvim }
    - { folder: start, repo: nvim-lua/plenary.nvim }
    - { folder: start, repo: vim-scripts/dbext.vim }
    - { folder: start, repo: jbyuki/venn.nvim }
    - { folder: start, repo: jbyuki/one-small-step-for-vimkind }
    - { folder: start, repo: fatih/vim-go}
    - { folder: opt, repo: nvim-treesitter/nvim-treesitter }
    - { folder: opt, repo: nvim-treesitter/playground }
    - { folder: opt, repo: saltstack/salt-vim }
    - { folder: opt, repo: vmchale/dhall-vim }
    - { folder: opt, repo: hashivim/vim-terraform }
    - { folder: opt, repo: sirtaj/vim-openscad }
    - { folder: opt, repo: diepm/vim-rest-console }

- name: wait for git clone
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: git_clone_jobs
  until: git_clone_jobs.finished
  loop: "{{ git_clone.results}}"

- name: Checkout vim dev plugins
  git:
    repo: https://github.com/{{ item }}
    dest: ~/.config/nvim/pack/plugins/start/{{ item | basename }}
    update: false
  loop:
    - mfussenegger/nvim-jdtls
    - mfussenegger/nvim-fzy
    - mfussenegger/nvim-lint
    - mfussenegger/nvim-dap
    - mfussenegger/nvim-dap-python
    - mfussenegger/nvim-treehopper
    - mfussenegger/nvim-lsp-compl
