---
- name: Get openapi generator
  get_url:
    url: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/3.3.4/openapi-generator-cli-3.3.4.jar
    dest: ~/apps/openapi-generator-cli.jar
    checksum: sha256:24cb04939110cffcdd7062d2f50c6f61159dc3e0ca3b8aecbae6ade53ad3dc8c
- name: Get jol
  get_url:
    url: https://repo1.maven.org/maven2/org/openjdk/jol/jol-cli/0.12/jol-cli-0.12-full.jar
    dest: ~/apps/jol.jar
    checksum: sha256:95517ad43c185d8fba3bc3599278d31edc01a98233e07e2adafe63ad264b7e12

- name: add gh-cli apt-key
  become: true
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg

- name: add gh-cli apt repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main' 
    state: present
    filename: gh
    update_cache: yes

- name: install gh-cli
  become: true
  apt:
    name: gh
    state: present
    update_cache: yes

- name: add docker apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker.gpg

- name: add docker apt repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable'
    state: present
    filename: docker
    update_cache: yes

- name: install docker-ce
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: install docker-ce-cli
  become: true
  apt:
    name: docker-ce-cli
    state: present
    update_cache: yes

- name: install containerd.io
  become: true
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: install docker-compose-plugin
  become: true
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

# vale from aur is outdated
- name: Get vale
  unarchive:
    src: https://github.com/errata-ai/vale/releases/download/v2.20.0/vale_2.20.0_Linux_64-bit.tar.gz
    dest: ~/bin/
    remote_src: true
    creates: ~/bin/vale

- name: Install Jekyll
  command: gem install jekyll bundler
